# Generated by Django 2.2.5 on 2019-09-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
